services:
  bot:
    dns:
      - 83.220.169.155
      - 212.109.195.93
    build: .
    image: botik
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GLHF_API_KEY: ${GLHF_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
      ADMIN_USER_ID: ${ADMIN_USER_ID}
      DATABASE_FILE: ${DATABASE_FILE}
      CHAT_PROVIDERS: ${CHAT_PROVIDERS}
      IMAGE_PROVIDERS: ${IMAGE_PROVIDERS}
      WEB_SEARCH_PROVIDERS: ${WEB_SEARCH_PROVIDERS}
      PROVIDER_MODELS: ${PROVIDER_MODELS}
    volumes:
      - /home/chebyrek/data/:/data
    restart: always
